# Generated by Django 4.2.24 on 2025-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_path',
            field=models.CharField(blank=True, help_text="Static path like 'images/covers/es/my-book.jpg'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('fantasy', 'Fantasy'), ('sci_fi', 'Sci-Fi'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('history', 'History'), ('children', 'Children'), ('romance', 'Romance'), ('classics', 'Classics'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('sv', 'Swedish')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
